/*
 * This file is part of Giro Jogos.
 * 
 * Giro Jogos is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 * 
 * Giro Jogos is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License
 * along with Giro Jogos. If not, see <https://www.gnu.org/licenses/>.
 */

// File generated by FlutterFire CLI.
// This is a placeholder - replace with actual Firebase configuration
// Run: flutterfire configure --project=your-project-id

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD390FMHXzTKPWPivhvZnFpkc6KSI9_pLI',
    appId: '1:820256283325:web:e7a2aad8ab708910c7f5d4',
    messagingSenderId: '820256283325',
    projectId: 'giro-jogos',
    authDomain: 'giro-jogos.firebaseapp.com',
    storageBucket: 'giro-jogos.firebasestorage.app',
    measurementId: 'G-TGT6K2NQXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo9nV9XJQ3aliZ8ZvsQj_JUYJcjx24xRY',
    appId: '1:820256283325:android:1e97a199c3bab8c6c7f5d4',
    messagingSenderId: '820256283325',
    projectId: 'giro-jogos',
    storageBucket: 'giro-jogos.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF8qBHpKf2iwiDkPe8EBecU-TPreTDp78',
    appId: '1:820256283325:ios:f70d86331ccda4a3c7f5d4',
    messagingSenderId: '820256283325',
    projectId: 'giro-jogos',
    storageBucket: 'giro-jogos.firebasestorage.app',
    iosBundleId: 'giro.giroJogos',
  );
}
