name: iOS Build (Optimized)

on:
  push:
    branches: [ main ]
    paths: 
      - 'lib/**'
      - 'ios/**'
      - 'pubspec.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'ios/**'
      - 'pubspec.yaml'

# Cancelar builds anteriores se houver um novo push
concurrency:
  group: ios-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios-fast-build:
    runs-on: macos-14  # Usar runner mais recente
    timeout-minutes: 45  # Timeout para evitar builds infinitos
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # Clone superficial para acelerar
      
      # Cache super agressivo para CocoaPods
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ios/Podfile.lock
            ~/.cocoapods/repos/trunk
            ~/Library/Caches/CocoaPods
          key: pods-v3-${{ runner.os }}-${{ hashFiles('ios/Podfile.lock', 'pubspec.yaml') }}
          restore-keys: |
            pods-v3-${{ runner.os }}-
            pods-v2-${{ runner.os }}-
      
      # Cache para builds Flutter iOS
      - name: Cache Flutter iOS builds
        uses: actions/cache@v4
        with:
          path: |
            build/ios
            ios/Flutter/ephemeral
            ios/.symlinks
            ios/build
          key: flutter-ios-v3-${{ runner.os }}-${{ hashFiles('pubspec.yaml', 'lib/**') }}
          restore-keys: |
            flutter-ios-v3-${{ runner.os }}-
            flutter-ios-v2-${{ runner.os }}-
      
      # Setup Flutter com cache
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true
          cache-key: flutter-v3-${{ runner.os }}
      
      # Cache das dependências pub
      - name: Cache Pub dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
            .dart_tool
          key: pub-v3-${{ runner.os }}-${{ hashFiles('pubspec.yaml') }}
          restore-keys: |
            pub-v3-${{ runner.os }}-
            pub-v2-${{ runner.os }}-
      
      # Instalar dependências
      - name: Install Flutter dependencies
        run: flutter pub get
      
      # Build iOS usando script otimizado
      - name: Build iOS 
        run: |
          chmod +x scripts/ci_build_ios.sh
          ./scripts/ci_build_ios.sh
        timeout-minutes: 30
      
      # Upload dos artifacts apenas se necessário
      - name: Upload iOS build (only on main)
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: ios-runner-app
          path: build/ios/iphoneos/Runner.app
          retention-days: 7
      
      # Notificação de sucesso
      - name: Build Success Notification
        if: success()
        run: |
          echo "✅ iOS build completed successfully in $(date)"
          echo "Build time: $(date -d @$(($(date +%s) - ${{ github.event.head_commit.timestamp }})) -u +%H:%M:%S)"